# Generated by Django 4.0.3 on 2022-05-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombreUsuario', models.CharField(max_length=30, unique=True)),
                ('correo', models.EmailField(max_length=60, primary_key=True, serialize=False, verbose_name='email')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
