# Generated by Django 4.0.3 on 2022-05-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioEducacionContinua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idText', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('numAsistencias', models.IntegerField(default=0)),
            ],
        ),
    ]
