# Generated by Django 4.0.3 on 2022-05-14 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ServicioEducacionContinua', '0001_initial'),
        ('ServicioAtencionPsicologica', '0001_initial'),
        ('ServicioBolsaEmpleo', '0001_initial'),
        ('Estudiante', '0001_initial'),
        ('ServicioMentoria', '0001_initial'),
        ('ServicioCurso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalAcompañamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numAsistencias', models.IntegerField(default=0)),
                ('estudiante', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Estudiante.estudiante')),
                ('sAtPsicologica', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ServicioAtencionPsicologica.servicioatencionpsicologica')),
                ('sBoEmpleo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ServicioBolsaEmpleo.serviciobolsaempleo')),
                ('sCurso', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ServicioCurso.serviciocurso')),
                ('sEdContinua', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ServicioEducacionContinua.servicioeducacioncontinua')),
                ('sMentoria', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ServicioMentoria.serviciomentoria')),
            ],
        ),
    ]
