# Generated by Django 4.0.3 on 2022-05-14 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estudiante', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversionista',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('estudiantes', models.ManyToManyField(related_name='est+', to='Estudiante.estudiante')),
            ],
            options={
                'abstract': False,
            },
            bases=('Usuario.usuario',),
        ),
    ]
