# Generated by Django 4.0 on 2022-05-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0002_initial'),
        ('Inversionista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversionista',
            name='estudiantes',
            field=models.ManyToManyField(related_name='est+', to='Estudiante.Estudiante'),
        ),
    ]
